services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_DB: 'postgres_db'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'password'
    env_file:
      - .env
    ports:
      - "5432:5432"